---
title: ""
author: ""
date: ""
output: 
  html_document: 
    css: hessen_style.css
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r, warning=FALSE}
library(chorddiag)
m <- matrix(c(0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
              0, 0, 1, 0, 2, 0, 0, 1, 1, 3, 0, 2,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 3,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 4,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 5,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 6,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 7,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 8,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 9,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 10,
              2, 1, 0, 3, 2, 0, 1, 0, 0, 0, 0, 11,
              1,  4,  1, 0, 1, 2, 3, 1, 1, 2, 1, 12),
            byrow = TRUE,
            nrow = 12, ncol = 12)
haircolors <- c("EU 2018/2048", "EU 2021/1139", "HVBIT", "EN 301 549", "OZG", "BGG", "BITV 2.0", "HessBGG", "WCAG 2.1", "HEGovG", "EU 2018/1524", "Richtlinie (EU) 2016/2102")
dimnames(m) <- list(have = haircolors,
                    prefer = haircolors)
Hessen <- c("#194343", "#2d4f9e", "#d4232e", "#eebb35", "#245f5f")
Hide_Tool <- c(FALSE)
Hide_Ticks <- c(FALSE)
chorddiag(m, groupColors = Hessen, showTooltips = Hide_Tool, showTicks = Hide_Ticks, groupPadding = 5)
m
```